spring.application.name=hotel-booking

spring.datasource.url=jdbc:mariadb://localhost:3306/hotel_booking_db
spring.datasource.username=root
spring.datasource.password=sapassword
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.config.import=optional:classpath:application-secret.properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Cloudinary Configuration
cloudinary.cloud-name=de9faei4p
cloudinary.api-key=238178722264727
cloudinary.api-secret=fbWzfemTaqVMb_YLzOYsNUhyHXM

# OpenAI Configuration
spring.ai.model.chat=openai
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.7